name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - aiohttp
  - cartopy
  - cdo  # unavailable on Windows; use Conda with WSL
  - cfgrib
  - dask
  - geopandas
  - intake-esm
  - mapclassify
  - matplotlib
  - nc-time-axis
  - netcdf4
  - odfpy
  - pooch
  - rasterstats
  - rioxarray
  - seaborn
  - pytest-cov
  - jupyterlab
