name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - aiohttp
  - cartopy
  - cdo  # unavailable on Windows; use Conda with WSL
  - cfgrib
  - dask
  - geopandas
  - intake-esm
  - mapclassify
  - nc-time-axis
  - netcdf4
  - odfpy
  - pooch
  - rasterstats
  - rioxarray
  - seaborn
  - statsmodels
  - pytest-cov
  - jupyterlab
  - pylint
  - flake8
  - black-jupyter
  - myst-nb
  - pydata-sphinx-theme
