name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dask
  - rioxarray
  - geopandas
  - intake-esm
  - cartopy
  - aiohttp
  - odfpy
  - cfgrib
  - netcdf4
  - pooch
  - rasterstats
  - cdo  # unavailable on Windows; use Conda with WSL
  - matplotlib
  - nc-time-axis
  - seaborn
  - mapclassify
  - qgis
