name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dask
  - matplotlib
  - rioxarray
  - geopandas
  - intake-esm
  - cartopy
  - nc-time-axis
  - aiohttp
  - odfpy
  - seaborn
  - cfgrib
  - pooch
  - cdo  # unavailable on Windows; use Conda with Windows Subsystem for Linux
  - pytest
  - rasterstats
