name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dask
  - matplotlib
  - rioxarray
  - geopandas
  - intake-esm
  - cartopy
  - nc-time-axis
  - aiohttp
  - odfpy
  - seaborn
  - cfgrib
  - pooch
  - rasterstats
  - cdo  # unavailable on Windows; use Conda with WSL
  - xesmf  # unavailable on Windows; use Conda with WSL
  - esmpy=8.3.1  # module name change compatibility for xesmf
  - cf_xarray
  - sparse
  - numba
  - mpi
  - pytest
